Basic site
ometman/Hello-world pull request #1
Opened 2022-11-30 03:31 UTC by ometman

Project complete 1

2022-11-30 04:33 UTC, ometman commented
Project Completed

2022-11-30 05:25 UTC, amejid requested changes
Hi @ometman, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>
## Highlights
- Linter checks are passing :heavy_check_mark: 
- Professional commit messages :fire: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 05:25 UTC, amejid commented on .gitignore
> +!README.md
- [ ] Kindly remove these two lines and put `test.md` so it will be prevented from getting tracked by git.
Since the `test.md` file is present in the repository you can remove it manually and commit your work after updating the `.gitignore` file.

2022-11-30 05:25 UTC, amejid commented on index.html
> +</html>
- [ ] Kindly update your Pull Request description to be more descriptive as it is the first thing that provides information on changes introduced in the project.
It's looking like this at the moment.
![image](https://user-images.githubusercontent.com/17243325/204713128-c50ca228-80d9-467c-9f13-c422d42e3e78.png)
You can refer this [material](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to get more information on how to write a descriptive PR. 🥸️

- [ ] Kindly try to make your README file free from broken links. 😎️
When trying to open this link it is giving back `404 Not Found` error.
![Screenshot from 2022-11-30 08-03-29](https://user-images.githubusercontent.com/17243325/204713968-d7ccb8c4-0965-4550-abbd-af8d05160ac2.png)
You can grab a `MIT.md` file from this [repository](https://github.com/microverseinc/readme-template) add it to your own as it will make the repo more professional.

2022-11-30 09:37 UTC, ometman commented on .gitignore
> +!README.md
test.md is added, and !README.md and *.md removed in .gitignore. Thank you.

2022-11-30 09:44 UTC, ometman commented on index.html
> +</html>
PR comment corrected and MIT license added with link. Thank you.

2022-11-30 10:14 UTC, Alfredbis29 requested changes
Hi @ometman , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️

Please ensure that linters are appropriately configured so that they can run to verify that your pull request is free of errors. I advise you to read this after taking a moment to reflect.[ lesson](https://github.com/microverseinc/linters-config/blob/master/html-css) to understand it clearly and follow the guideline to set it correctly.
You should consider to run this command:

`To install webhint depencies: npm install --save-dev hint@7.x Stylelint: npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x`

Kindly fix this :point_down: 
![manuta](https://user-images.githubusercontent.com/88894525/204769311-8765a7cf-c6aa-4856-81d1-2d1d0a40ef78.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 22:57 UTC, emmiiorji approved these changes
Hi @ometman , 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/204921935-8884c611-a2b5-4af5-81d5-aff598294d41.gif)

## Good Highlights

- Linter checks are passing
- Good commit messages
- Requested changes have been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 08:06 UTC, merged

2022-12-01 08:09 UTC, ometman commented
The project was a very good practice. It helped to recap few things.

2023-01-11 00:38 UTC, Owusu-Desmond reviewed
Hi @ometman , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._